name = "Packwiz Skyfactory 3"
author = "zenware"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f4b834d96fcee0febeabea29c651899a80bf2477699e80429f496f710b168a8"

[versions]
forge = "12.18.3.2511"
minecraft = "1.10.2"
quilt = "0.16.0-beta.16"
