name = "Packwiz Skyfactory 3"
author = "zenware"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7527b13467b8d6574a7b932a1b7c34a42594e28c32dbc79d2442648a2b5ca129"

[versions]
forge = "12.18.3.2511"
minecraft = "1.10.2"
quilt = "0.16.0-beta.16"
