name = "AutoRegLib"
filename = "AutoRegLib-1.0-2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2327/403/AutoRegLib-1.0-2.jar"
hash-format = "sha1"
hash = "22c12d61dd4f3179b9a56ba11da71cbf56747006"

[update]
[update.curseforge]
file-id = 2327403
project-id = 250363
