name = "Bed Bugs"
filename = "BedBugs-1.10.2-1.1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2399/523/BedBugs-1.10.2-1.1.6.jar"
hash-format = "sha1"
hash = "094c7f78cf498dcdde2a7ef4bb642fbc0937bb8e"

[update]
[update.curseforge]
file-id = 2399523
project-id = 254508
