name = "Clumps"
filename = "Clumps-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2384/158/Clumps-1.0.5.jar"
hash-format = "sha1"
hash = "7b71266d3af3e83b3866d7143097221268ad3551"

[update]
[update.curseforge]
file-id = 2384158
project-id = 256717
