name = "CodeChicken Lib 1.8.+"
filename = "CodeChickenLib-1.10.2-2.5.9.283-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2447/314/CodeChickenLib-1.10.2-2.5.9.283-universal.jar"
hash-format = "sha1"
hash = "073fcda1536b9fadf27607dae6fbabb491548dd2"

[update]
[update.curseforge]
file-id = 2447314
project-id = 242818
