name = "Decocraft"
filename = "Decocraft-2.5.2_1.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2495/133/Decocraft-2.5.2_1.10.2.jar"
hash-format = "sha1"
hash = "bd6c4d61867fd5647b17a951f14fc68b2b5973e4"

[update]
[update.curseforge]
file-id = 2495133
project-id = 79616
