name = "Experience Rings"
filename = "xprings-1.10-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2360/296/xprings-1.10-1.3.0.jar"
hash-format = "sha1"
hash = "e791ed52561c15fe1cf43a616590ddfdda7f863e"

[update]
[update.curseforge]
file-id = 2360296
project-id = 243060
