name = "Fairy Lights"
filename = "fairylights-2.1.3-1.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2513/424/fairylights-2.1.3-1.10.2.jar"
hash-format = "sha1"
hash = "d3f67ffeb9206483d8fc6eb16667239dd4acaf28"

[update]
[update.curseforge]
file-id = 2513424
project-id = 233342
