name = "Inventory Sorter"
filename = "inventorysorter-1.10.2-0.11.0+47.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2400/85/inventorysorter-1.10.2-0.11.0+47.jar"
hash-format = "sha1"
hash = "4e269391d9a217eb166235f4770fa5c0ea24198b"

[update]
[update.curseforge]
file-id = 2400085
project-id = 240633
