name = "Neat"
filename = "Neat 1.3-12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2327/663/Neat%201.3-12.jar"
hash-format = "sha1"
hash = "ff116be38dec04ba792bf685427bb606a874917d"

[update]
[update.curseforge]
file-id = 2327663
project-id = 238372
