name = "Not Enough Items 1.8.+"
filename = "NotEnoughItems-1.10.2-2.1.3.220-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2413/865/NotEnoughItems-1.10.2-2.1.3.220-universal.jar"
hash-format = "sha1"
hash = "837b5e927b55af49d6ee1b4898674b96daad5ed9"

[update]
[update.curseforge]
file-id = 2413865
project-id = 247694
