name = "OpenBlocks Elevator"
filename = "ElevatorMod[V.1.3.0][MC.1.10.2].jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2353/263/ElevatorMod%5BV.1.3.0%5D%5BMC.1.10.2%5D.jar"
hash-format = "sha1"
hash = "f97d6e89e90ea7c5d77de22ca78c7e9f890a7b8e"

[update]
[update.curseforge]
file-id = 2353263
project-id = 250832
