name = "Resource Loader"
filename = "ResourceLoader-MC1.9.4-1.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2307/834/ResourceLoader-MC1.9.4-1.5.1.jar"
hash-format = "sha1"
hash = "08d4595147ab23bce3bb99da52153e4fa7c1b122"

[update]
[update.curseforge]
file-id = 2307834
project-id = 226447
