name = "Simply Jetpacks 2"
filename = "SimplyJetpacks2-1.10.2-2.1.3.55.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2437/53/SimplyJetpacks2-1.10.2-2.1.3.55.jar"
hash-format = "sha1"
hash = "5d7390010bb6a382c55619f9328e319961ee8e11"

[update]
[update.curseforge]
file-id = 2437053
project-id = 251792
