name = "Storage Drawers"
filename = "StorageDrawers-1.10.2-3.7.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2446/106/StorageDrawers-1.10.2-3.7.10.jar"
hash-format = "sha1"
hash = "b6db0cfbdb7ad98b09e3c8e21ee39dcb3036aa3d"

[update]
[update.curseforge]
file-id = 2446106
project-id = 223852
